# This workflow just verifies that the docs build without any
# warnings (as configured in the tox recipe). This is only run on
# the test-me-* branches and PRs as pushes to main will trigger the docs
# workflow.
name: check-docs

on:
  push:
    branches: [test-me-*]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check-docs:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install packages
        run: pip install --upgrade setuptools pip tox

      - name: Run tox to build docs
        run: tox -e docs
