name: tests

on:
  push:
    branches: [main, test-me-*]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  unit:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install packages
        run: pip install --upgrade setuptools pip tox

      - name: Run tox
        run: tox -e py

      - name: Verify proxystore home directory not created
        run: |
          # The home directory could be any of the following
          if [[ -n $PROXYSTORE_HOME ]]; then test ! -d $PROXYSTORE_HOME; else true; fi
          if [[ -n $XDG_DATA_HOME ]]; then test ! -d $XDG_DATA_HOME/proxystore; else true; fi
          test ! -d ~/.local/share/proxystore
